# Get me ubunty 14.04 trusty
sudo: required
dist: trusty

services:
  - docker

before_install:
  # set up dotnet
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install -y dotnet-dev-1.0.0-preview2.1-003177
  # set up aws cli
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  # docker build webservice
  - docker build -t bootstrap-webservice ./WebService
  # docker build workerservice
  - docker build -t bootstrap-workerservice ./WorkerService

script:
  - dotnet restore
  # WebService test
  - dotnet test ./WebService.UnitTests/ -parallel none
  # - run docker container
  # - run any integration tests on the container using scripts
  # WorkerService test
  - dotnet test ./WorkerService.UnitTests/ -parallel none
  # - run docker container
  # - run any integration tests on the container using scripts

branches:
  only:
  - master

after_success:
  - $(aws ecr get-login --region us-east-1) # does docker login
  # webservice docker push
  - docker tag bootstrap-webservice:latest 047651431481.dkr.ecr.us-east-1.amazonaws.com/bootstrap-webservice:$TRAVIS_JOB_NUMBER
  - docker push 047651431481.dkr.ecr.us-east-1.amazonaws.com/bootstrap-webservice:$TRAVIS_JOB_NUMBER
  # workerservice docker push
  - docker tag bootstrap-workerservice:latest 047651431481.dkr.ecr.us-east-1.amazonaws.com/bootstrap-workerservice:$TRAVIS_JOB_NUMBER
  - docker push 047651431481.dkr.ecr.us-east-1.amazonaws.com/bootstrap-workerservice:$TRAVIS_JOB_NUMBER

