# Get me ubunty 14.04 trusty
sudo: required
dist: trusty

services:
  - docker


env:
  global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - secure: FTOP/SHem124GMHhvpPiyA7s707qrp0Lw9Sg0Xt3Mf3Ya1C/UBDmLM3GYR299CxH+HOA+8XdOsC6GH7oRULyhxL01COmtt0Agezg5+4fx0Jd3zzlWsvW/E4ZkIEgipkLeDt305qWzXptxGy7+N/QiLV7Bt/ZFy7oL744chare5i1opcQhNFXytyjcY7zc3cfhSksKoJMYNgGn0HltTpaBqnaMVypIiWdRKAgRYbeK8E4duGucfJnF3wTkJ6Cjafccl1TnVhQsBfG4VOBrwL5EH8vVOqUXUV/H+R8WVEPUUUIeDvsPZ8gmSZFTTl8nVmdGCFmWF0b0iHcRtiZy65QB2cAPXMHHTrjcdVaCMdpWOP/i7o3mhgAoEZV2RL/9+KgmuqqSsAHTKVaoCI5nR1I58trZLvA9L88NLhYgVEgm7ME6t93litUCytFBfHuh32WyxMZA7cZ6QI6EiIIcu2fuZ8e9dX5B27L8ivESttMzHW+yGbeyf697b8cuEjFdKhJYlERrqxKFlLRTXF1wpGTBqZ2Wt1r9m8e/xtQ8BMX6aKROOXKsg6Ym8LWF/iAUnGlAHlZDN2DA2bNzln/fw1PVvtqAWYfKTmcJZzBMb2rka7mmQ29tYgEtPdmwdO7zkTolxKJS+irZRN5XfcFB4UMvtXpxh1YFFArdIC5vBcpep4=
  - secure: CZL+BHgY3i/04Tk1O0ekBLWR+bv0jz+fIYHuFVGHJ/EC82Fkw04f0u9arvmArRXxHLNeIJK9yCMeEhT6gITdV6nzWUxXUtZRtXaEE2x8v4DIOm8MN3YJh8QAdYuSFyF2RP4+4KN3Gb9fKvnUj5HuJ2S8oKhhtYjeWuwA+fbtbZO6kf9ZWF4hMBmQZizIAsWEXzqOK3a2N4i87v9uesYoet7Nd2fGB1RJkNB+IVIw5oN7MOC7bbnCRhqWIwAhd8LOqH9hqXTqJHvl/A4N+wwiJ6PASo24Uegsutow9+60h3hvz4BvlD4Jd1TuFJl0/u7kQiNM7bVtgGUVVubBPAerNP0WeQwRFUPYS0/RI8Mw96WcDz55kByMdzRxIRFZW83WkRhjxy7YghJ9xkUzpg4MBWPs4nT5VRLWbYWYijofbwWXHSsXC/Mqg5ujZjYkkZpTIZ78vNWLL3MCrVtuwXEP5p65UHm9+yS8W+0h6eS/stTqLfANE+sGl/u+kFIxOfj9zrGabLffp9k4Dl5D53cVUdcqOou+GOyexvhcDqLMVxVD78SmgbppuMs/cla8Wb0IGdLpcm0OazUrxqHk7+5Z0PwWQtEwxDCryczCPb0mHIhf17j7Q2rfPoYGgDasmft9GZ8DQJEgg2GdVmqkV+IgPiTpEh0NGouJztzN040nO9I=
  - secure: gxhLvqBXRrR65qiSFfLYQXHlV/al1rufYHpcax11FQjCsk1hS7jKdWTtUBIxKgeqU8VcOfTlX+wK4HoTR/wrh4YvxI0FayAB+amhAJvQ0NyjF4YIJhE6pPcvyHhRcu7I0F0OMmYdfWzusNDkNJN3KE017utd/u35aZsM41TwyCtWmhg94dFj+4ZDypsiLhWfpRbrcpOdPK0aat/movwvV1NGbuLlAI+wlYn26Zc+LwtZVpHDk/zI69Dwek7BjQVch1mAOuxsLCcXflv08PGioxtCcBxp1U0zmhsFOz99IJGAECdtrBWW0ySFcGQU3X34v+6OYhSp1QXpkUUa7yeLlDHIBo6t10QD7y62KmeOMF7Ys0P98A/gXlQvvGqoQ+fdL+RnahPlzHKnJNsNcXvCy4nW+lyhR9F0YBJBhUJDSFsw4dcLRTEUssj63QbtOOyUyFFMeObfd50RDJlWwf+2Y66Qc5VUKCx/0bcZQVJ6ovQqMg0VA1k7j1+zqXIwnr9Ih5ZAJ4Z7R38nkFXmgZ6hzl79bHjXRj0RLsR8IOfTazEzt7d8in65SmPx9tpJ5V3f3HTbvs9Q7B+e3u/LcRTm5taD2jPk7ODs2GK/7iYvT4ne2pPwnh6RVC7INMHmu2IUYqJWu0qOqdDtUSuowF3LWCUtmowTlWAE0MslyzQZ1D4=
  - secure: dPUNVXBRtHUn3x2VBLits/ewy4UZY0jREE6YKR9wREn9qHU0Wy283QbcDK7D/nEmuVQKK/1ALYaP3zr5WMrGP4rZCcyuaxXRTwPJgUOguhsY3DuU++jrZk1mdOikvUfOk9fMTckMBh+L0mvZuoWJVuo4TWw7/gZaF7SRFurVYzyqWm3m5lly5hngkP1zOoPdPRRJ5rnGvgp7imGZ4GrCkpXHEzeCmZPXXaHAygZeXBtw9m11MXaD5hpmzElf0gGQg0CgrwWDuoopfot+2DEShGc32dbYgCZTymysSpSfNCkjG/9q2LMJfu2TB79ru5AQRMAvOTBGhv+U3oP7fUw+o/fkArYB0C7nEb40ArLZnYUmpxuaRdHfVblPsOUZgN4eoZPggO3QdlLlA+scDUK4HtNvLo3ioJIPc+VFpGeGarUjaXuz/c8aj3Ctm6oAdPgyx0yQnBD8qIHV+/J4a1kD8RbofHJmEeKfnBGN+WagBjIlR9J58G3d/LPwZVjfKwuoJf/8q8ZoJk5yu8vMP8DOdarFL1+SfpldB5wwl2NEVSDFqWYnqnBJyeTbC2NzI7zpa6+bcMjmfA8DYMCmm/DoibkaAnbKJPUo8dd6Y3z3TAInVNq1qkSbxUqM3eZCgK4YUl0zVOAXToaKXmPwTrZFbFhLTQgOHu6hMelnFGuRQco=
  - secure: FUfhiKM9xCxo9ug9BRZrROyg47Fh0JK3+9BkMENR9p5RQfNd89f+z/p7StXCTCDED8NLg5U8Kg9Nf8HIyyYqbNNUCBEjWYnVhIoIMDHhalqsJvnKU9z7xawaJsQhmCLmE46qB7WLIVklzAEGIc7gxC1LH+OimxT6S7rQcIO3Rn5Arif/nvtYg8VEDXSYxTi/r/3FjvbDNAvbFrlN5OrX4Y/HMQHiZyng3cAKHSX/P1UoeATmLcNkl8PC8aAzckM3Fwx58s33KNppjoWaPo8TVp+U3v3NXoAU8ce2GtRAIOGTL/WSSiVqohka53S9lBt2G7SNajQGuHgiysHL1tqX94rWmvXm8thvPP8XLBgUsHJP/L0BAQKGsnkbn/adcoTabYjc/m9FD+H0suQdhDAEZz4GCddbnIBCRZjaodDsYPaa9aKygCvM1vjwqguFH2dAmnC8xCXoeER83yX6k5tWJU+dqGHD3JFHu7Tjo8K2EGWnz/taQqlbZ/jkXgOaXKm/AXQxxovpJcJ+IsxBbak/76xuP2Y6oaYctnwH64K01LAqvTFgm8KzcivRtdNoopeJUhsLujR5a4gsrdbC1snJrD8FIo9bRrJ26zE/2cFGGtHQrfXXYJezA5kzrU3FaFuT2J+p49Sjm8cyD1e15+yYF9w/cCRvkpjo1zAhqJmLMls=
  - secure: Yb+rNzOERD+hzAEm9kenpzuifR75Mejq685Z+EQmHz/bXUp1iuczqoEgd4SiwYmLWXW2GWERjVonByZfCdb1FzepIhgOa57SiKGdO/s1cxO44/Z5xUPI+hEJWW3xoiDOilCf2E9Emd/LTAHaxyLhxoxJJtr+1ffF6jLjPFhgmSnymCDHNPzAxA/3w0shpZ65v4sbfVs6766d1sJCfz3CWPnP7apDqnNDkZ0ZXY5zosLVuzwumTZl44Y8SMM6+3T6AUVlEmB03ByVkIX6FnOUANRUGTFr8fB7M+8bZ06NsOZ6BRhF39VyhGOuOe1rL+M4CBzn7HakOGdLNUNzFsHmioB6Wy68NYtPw1PZIoyNOIGW4Ng6IaZ3aEeduTE4wTA2VQwWRQ8c34R78vEfnpd21xkUeFLX9LTEob0XPihpYNT6y3bAGftRAWVLQsOeQmotKDQUSp5AyNlaP6JoDCQ0F7+OasIm8TwUKF41OKuGRv9iiPEm2uTJYXCQFuGw0IHslBbBSyCweyBxqSxwmlpExoKrXE7gPfMj7ttNpY/AKOMWfeqYwphRXsO5RKlwwWnKjeyy2H+FxrR/kdkmUnAvIBxGlwY32+q2JQTSbj8Y8JT3AZ8zaxpgby6eboaZhqHeXH66Xec8J45OLfDBGCuTGyYZl6MVrzJ1ozqhN25uWoE=
  - BUILD_NO=$TRAVIS_BUILD_NUMBER

before_install:
  # set up dotnet
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install -y dotnet-dev-1.0.0-preview2.1-003177
  # set up aws cli
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  # docker build webservice
  - docker build -t launchpad-webservice ./WebService
  # docker build workerservice
  - docker build -t launchpad-workerservice ./WorkerService

script:
  # WebService test
  - dotnet restore ./WebService.UnitTests/
  - dotnet test ./WebService.UnitTests/ -parallel none
  # - run docker container
  # - run any integration tests on the container using scripts
  # WorkerService test
  - dotnet restore ./WorkerService.UnitTests/
  - dotnet test ./WorkerService.UnitTests/ -parallel none
  # - run docker container
  # - run any integration tests on the container using scripts

branches:
  only:
  - master

after_success: 
  - ./deploy.sh
