# Get me ubunty 14.04 trusty
sudo: required
dist: trusty

services:
  - docker

before_install:
  # set up dotnet
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install -y dotnet-dev-1.0.0-preview1-002702
  # set up aws cli
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  # docker build webservice
  - docker build -t launchpad-webservice ./WebService
  # docker build workerservice
  - docker build -t launchpad-workerservice ./WorkerService

script:
  # WebService test
  - dotnet restore ./WebService.UnitTests/
  - dotnet test ./WebService.UnitTests/ -parallel none
  # - run docker container
  # - run any integration tests on the container using scripts
  # WorkerService test
  - dotnet restore ./WorkerService.UnitTests/
  - dotnet test ./WorkerService.UnitTests/ -parallel none
  # - run docker container
  # - run any integration tests on the container using scripts

branches:
  only:
  - master
  
after_success:
  - ./deploy.sh
